### ISSUE TITLE
SRS review

### ISSUE THREAD

**Issue by smiths** [yanxuanm/CAS741#10]
@ernsthjm please review the SRS for @yanxuanm.

**Comment by JohnErnsthausen** [comment]
Will do. Actually done, but must open issues which I'll do momentarily.

**Comment by JohnErnsthausen** [comment]
These instructions say how to close issues. I do not see a close issue button.

https://stackoverflow.com/questions/34010565/how-do-i-close-a-github-issue-without-making-a-commit#:~:text=1%20Answer&text=You%20can%20close%20an%20issue,button%20under%20the%20comment%20box.

**Comment by JohnErnsthausen** [comment]
Two previous comments for @smiths

**Comment by smiths** [comment]
@JohnErnsthausen, you might not have access to close issues.  I'll close it now.
