### ISSUE TITLE
R2 in SRS document

### ISSUE THREAD

**Issue by JohnErnsthausen** [yanxuanm/CAS741#22]
R2: Depending on your computing architecture, your processor may always work in double precision.

Calculation. To maintain data single precision (32-bit), during calculation, all intermediate variables should have double precision (64-bit). Also solver should using implicit approach for approximation, avoid divergence of the results.
@smiths @yanxuanm

**Comment by yanxuanm** [comment]
I am not quite get your issue here. single precision is a computer number format, usually occupying 32 bits in computer memory. Its just a format of number data be stored.

**Comment by JohnErnsthausen** [comment]
I'm not sure I can comment when you close the issue.

**Comment by JohnErnsthausen** [comment]
The short story is that modern 64 bit processors process the float as a double, ignoring the extra precision. You may as well just use double.

**Comment by yanxuanm** [comment]
This computation step doesn’t do much with process architecture. Some CG library uses algorithms with single precision. That’s why modern GPU has two benchmark categories. TFlops of single precision & double precision

**Comment by yanxuanm** [comment]
Also I think 64-bit is talking about the instruction set, it is not strictly related to how data should be manipulated in the memory.

**Comment by JohnErnsthausen** [comment]
Neither your SRS nor your VnV even mentioned GPU. Using the GPU creates at least one requirement about what hardware you're using and its capabilities. I'd have to defer to someone more knowledgeable on GPU programming and scheduling and performance tuning to engage in a meaningful conversation on that topic.

However my $0.02 for something to think about. Why use a GPU tool when you're going to be interactive with Matlab? Going interactive with Matlab will kill any performance gain from GPU.

Another $0.02. The CG libraries might use single precision, that's their business. Doesn't mean you have to use single precision when it's appropriate to do so.
