### ISSUE TITLE
Partial finished SRS. Will complete in a day or two.

### ISSUE THREAD

**Issue by yanxuanm** [yanxuanm/CAS741#3]
Hi Dr. @smiths, 

I don't think I can finish documents by the end of today. But I have several sections are now ready to review. 

https://github.com/yanxuanm/CAS741/blob/master/SRS/SRS.pdf

Section 2 & 3, and Section 4 until page 10.

I think I need one or two days to complete Theoretic models and instanced models. Sorry for the poor time management. This document is taking longer than I thought. 

Xuanming Yan

**Comment by smiths** [comment]
@yanxuanm, I've been asking everyone that has requested an extension to give me a specific date for their new deadline.  What deadline are you thinking?  Most people have asked for Saturday as a deadline.  Does that work for you?

**Comment by yanxuanm** [comment]
Thanks Dr. @smiths , Saturday works for me. 

Xuanming Yan

**Comment by smiths** [comment]
Okay, we'll make that Saturday your new deadline.  :smile:
