### ISSUE TITLE
Stanford bunny mesh

### ISSUE THREAD

**Issue by JohnErnsthausen** [yanxuanm/CAS741#32]
I don't know the Stanford bunny mesh. How does a mesh validate a computation? I just don't have much information to go on here.

@smiths @yanxuanm

**Comment by yanxuanm** [comment]
stanford bunny mesh is a mesh obj file from The Stanford 3D Scanning Repository. it is widely used in CG research. 

From wiki: 
Stanford bunny is a computer graphics 3D test model developed by Greg Turk and Marc Levoy in 1994 at Stanford University. The model consists of 69,451 triangles, with the data determined by 3D scanning a ceramic figurine of a rabbit.

**Comment by JohnErnsthausen** [comment]
Your project uses a mesh. What does a complicated mesh validate or verify in your code? That's my point. You USE a mesh.
