### ISSUE TITLE
System Context

### ISSUE THREAD

**Issue by moalaa** [yanxuanm/CAS741#7]
Hello Yanxuanm,

In System Context Section, I understand that the functionality of pre-processor and post-processor but both of them are implemented inside PAESolver Model, right?
If yes, then I think you shouldn't mention them here as system context should be abstract. 

![sc](https://user-images.githubusercontent.com/31176105/96464273-9dfa0500-11f5-11eb-9e51-2fc426f57b63.PNG)

**Comment by yanxuanm** [comment]
Those are not part of software.
